name: Flutter Build Test

on: push

permissions:
  actions: read
  contents: read

jobs:
  build:
    name: Test Build (Release)
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: microsoft
        java-version: "11"

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.3.10"

    - name: View Flutter status
      run: |
        flutter --version
        flutter doctor -v

    - name: Initialize project
      run: |
        flutter create --platforms android --project-name waifu .
        keytool -genkey -v -keystore android/app/upload-keystore.jks -storetype pkcs12 -keyalg RSA -keysize 2048 -validity 10950 -alias upload < ci/sample-keygen-input.txt
        cp ci/key.properties.txt android/app/key.properties

    - name: Analyze project
      run: flutter analyze -v

    - name: Test build
      run: flutter build apk -v
