name: Flutter Build Test

on: push

permissions:
  actions: read
  contents: read

jobs:
  build:
    name: Test Build (Release)
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: microsoft
        java-version: "11"

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.3.10"

    - name: View Flutter status
      run: |
        flutter --version
        flutter doctor -v

    - name: Initialize project
      run: flutter create --platforms android .

    - name: Analyze project
      run: flutter analyze

    - name: Test build
      run: flutter build apk
